name: Front-end CI
# Path: .github/workflows/front.yml
# Deploy to production as a node build

on:
  push:
    branches: [ master, dev, 28-ci ]
defaults:
  run:
    working-directory: front

jobs:
  build-front:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Tar files
        run: tar -cvf polyfrontier-front-new.tar /home/runner/work/ps7-21-22-caspar-wia2-21-22/ps7-21-22-caspar-wia2-21-22/front/dist

      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: polyfrontier-front
          path: |
            /home/runner/work/ps7-21-22-caspar-wia2-21-22/ps7-21-22-caspar-wia2-21-22/front/polyfrontier-front-new.tar
          retention-days: 1

    outputs:
      job_status: ${{ job.status }}

  deploy-front:
    runs-on: ubuntu-latest
    needs: [ build-front ]
    steps:
      - name: Download the built production artifact
        uses: actions/download-artifact@v2
        with:
          name: polyfrontier-front
          path: //home/runner/work/ps7-21-22-caspar-wia2-21-22/ps7-21-22-caspar-wia2-21-22

      - name: Display structure of downloaded files
        run: stat polyfrontier-front-new.tar
        working-directory: /home/runner/work/ps7-21-22-caspar-wia2-21-22/ps7-21-22-caspar-wia2-21-22

      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 55552
          source: "/home/runner/work/ps7-21-22-caspar-wia2-21-22/ps7-21-22-caspar-wia2-21-22/polyfrontier-front-new.tar"
          target: "/home/admin/source"

      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 55552
          script: |
            echo ${{ secrets.SERVER_PASSWD }} | sudo -S service polyfrontier-front stop
            cd /home/admin/source
            mv polyfrontier-front.tar polyfrontier-old.tar
            mv github/workspace/polyfrontier-front-new.tar polyfrontier-front.tar
            rm -r  polyfrontier-front
            tar -xvf polyfrontier-front.tar
            mkdir -p polyfrontier-front
            mv /home/admin/source/home/runner/work/ps7-21-22-caspar-wia2-21-22/ps7-21-22-caspar-wia2-21-22/front/dist/* polyfrontier-front
            rm -r home
            rm polyfrontier-front-old.tar
            echo ${{ secrets.SERVER_PASSWD }} | sudo -S service polyfrontier-front start